// <auto-generated />
using System;
using CornerShopApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CornerShopApi.Migrations
{
    [DbContext(typeof(CSDbContext))]
    [Migration("20260129191308_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CornerShopApi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "Ergonomic wireless mouse",
                            ImageUrl = "https://picsum.photos/seed/mouse/400/300",
                            Name = "Wireless Mouse",
                            Price = 19.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Blue switches mechanical keyboard",
                            ImageUrl = "https://picsum.photos/seed/keyboard/400/300",
                            Name = "Mechanical Keyboard",
                            Price = 59.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Description = "Fast charging 65W USB-C",
                            ImageUrl = "https://picsum.photos/seed/charger/400/300",
                            Name = "USB-C Charger",
                            Price = 24.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 4,
                            Category = "Fashion",
                            Description = "Lightweight running shoes",
                            ImageUrl = "https://picsum.photos/seed/shoes/400/300",
                            Name = "Running Shoes",
                            Price = 49.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sports",
                            Description = "Insulated steel bottle 1L",
                            ImageUrl = "https://picsum.photos/seed/bottle/400/300",
                            Name = "Water Bottle",
                            Price = 14.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Category = "Fashion",
                            Description = "Laptop backpack 15 inch",
                            ImageUrl = "https://picsum.photos/seed/bag/400/300",
                            Name = "Backpack",
                            Price = 39.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            Description = "Portable speaker with bass",
                            ImageUrl = "https://picsum.photos/seed/speaker/400/300",
                            Name = "Bluetooth Speaker",
                            Price = 29.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            Description = "Fitness tracking smartwatch",
                            ImageUrl = "https://picsum.photos/seed/watch/400/300",
                            Name = "Smartwatch",
                            Price = 79.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 9,
                            Category = "Home",
                            Description = "Ceramic mug 350ml",
                            ImageUrl = "https://picsum.photos/seed/mug/400/300",
                            Name = "Coffee Mug",
                            Price = 9.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 10,
                            Category = "Home",
                            Description = "LED desk lamp with dimmer",
                            ImageUrl = "https://picsum.photos/seed/lamp/400/300",
                            Name = "Desk Lamp",
                            Price = 22.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 11,
                            Category = "Stationery",
                            Description = "Hardcover notebook A5",
                            ImageUrl = "https://picsum.photos/seed/notebook/400/300",
                            Name = "Notebook",
                            Price = 6.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 12,
                            Category = "Stationery",
                            Description = "Smooth gel pen set (10)",
                            ImageUrl = "https://picsum.photos/seed/pens/400/300",
                            Name = "Pen Set",
                            Price = 8.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 13,
                            Category = "Sports",
                            Description = "Non-slip yoga mat",
                            ImageUrl = "https://picsum.photos/seed/yoga/400/300",
                            Name = "Yoga Mat",
                            Price = 18.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 14,
                            Category = "Sports",
                            Description = "Pair of 5kg dumbbells",
                            ImageUrl = "https://picsum.photos/seed/dumbbell/400/300",
                            Name = "Dumbbells",
                            Price = 34.99m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 15,
                            Category = "Electronics",
                            Description = "Over-ear noise isolation",
                            ImageUrl = "https://picsum.photos/seed/headphones/400/300",
                            Name = "Headphones",
                            Price = 44.99m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 16,
                            Category = "Fashion",
                            Description = "Cotton t-shirt regular fit",
                            ImageUrl = "https://picsum.photos/seed/tshirt/400/300",
                            Name = "T-shirt",
                            Price = 12.99m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 17,
                            Category = "Fashion",
                            Description = "Slim fit stretch jeans",
                            ImageUrl = "https://picsum.photos/seed/jeans/400/300",
                            Name = "Jeans",
                            Price = 39.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 18,
                            Category = "Home",
                            Description = "Non-stick frying pan 28cm",
                            ImageUrl = "https://picsum.photos/seed/pan/400/300",
                            Name = "Cooking Pan",
                            Price = 27.99m,
                            Stock = 32
                        },
                        new
                        {
                            Id = 19,
                            Category = "Home",
                            Description = "Queen size bedsheet set",
                            ImageUrl = "https://picsum.photos/seed/bedsheet/400/300",
                            Name = "Bedsheet Set",
                            Price = 24.99m,
                            Stock = 26
                        },
                        new
                        {
                            Id = 20,
                            Category = "Personal Care",
                            Description = "SPF 50 PA+++ sunscreen",
                            ImageUrl = "https://picsum.photos/seed/sunscreen/400/300",
                            Name = "Sunscreen",
                            Price = 11.49m,
                            Stock = 70
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CornerShopApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CornerShopApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CornerShopApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CornerShopApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
